export const dummy = [
    {
        "productDetail": {
            "unitPrice": 525.0,
            "productTypeNo": 106,
            "productMasterId": "e303d614-7593-4f76-9f73-f7a5d956caeb",
            "unitSize": "1 kg",
            "youtubeVideoUrl": "",
            "variantProducts": [],
            "type": "product",
            "descriptions": "",
            "productName": "Organic Malai Paneer",
            "productQuantity": 2000,
            "productImage": "https://i.imgur.com/cgrGvMf.png",
            "coverImage": "https://i.imgur.com/cgrGvMf.png",
            "maxQuantityForOffer": 90,
            "details": "",
            "trackInventory": true,
            "strikePrice": 700.0,
            "sameBrandProducts": [
                {
                    "id": "025b06a8-8c78-4b38-a65e-143160f67364",
                    "productName": "Organic Pizza Cheese",
                    "productUnitPrice": 1315.0,
                    "productImage": "https://i.imgur.com/fJhXg9p.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Pizza Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201477,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "8f6d176c-d894-4ffb-a992-14ae8e600215",
                    "productName": "Organic Mild Cheddar",
                    "productUnitPrice": 1315.0,
                    "productImage": "https://i.imgur.com/7YgyJ9l.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "mild cheddar",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201475,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "075f0fed-b196-4f09-b34e-1ec265f514ee",
                    "productName": "Akshayakalpa - A2 Farm Fresh Organic Milk",
                    "productUnitPrice": 44.0,
                    "productImage": "https://i.imgur.com/DrX4Bqo.png",
                    "productSubType": 1,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa - A2 Farm Fresh Organic Milk",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201431,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1849,
                    "trackInventory": true
                },
                {
                    "id": "22518868-d5b0-4e1d-a145-ba72c7969b5c",
                    "productName": "Akshayakalpa - A2 pasteurized milk",
                    "productUnitPrice": 43.0,
                    "productImage": "https://i.imgur.com/zeDYJlP.png",
                    "productSubType": 1,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "A2 pasteurized milk",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201432,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "f2f914b9-afee-45c4-98ba-c5a35d2794ee",
                    "productName": "Akshayakalpa - A2 Slim Organic Milk",
                    "productUnitPrice": 40.0,
                    "productImage": "https://i.imgur.com/l87giR8.png",
                    "productSubType": 1,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "A2 Slim Organic Milk",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201430,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1991,
                    "trackInventory": true
                },
                {
                    "id": "c242c693-e6f5-44b7-8f77-87c2b488f5f7",
                    "productName": "Akshayakalpa - organic milk",
                    "productUnitPrice": 35.0,
                    "productImage": "https://imgur.com/0vSeVmf.png",
                    "productSubType": 1,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa - organic milk",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201433,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 903,
                    "trackInventory": true
                },
                {
                    "id": "4811dceb-9ffd-46ec-bdd8-9d6c28ca8d05",
                    "productName": "Akshayakalpa - Organic Slim Milk",
                    "productUnitPrice": 30.0,
                    "productImage": "https://imgur.com/JK5J5rD.png",
                    "productSubType": 1,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa -Organic Slim Milk",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201434,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1971,
                    "trackInventory": true
                },
                {
                    "id": "55d8ea68-c5e6-4211-a48e-77ff663d745b",
                    "productName": "Organic Aged Cheddar",
                    "productUnitPrice": 1425.0,
                    "productImage": "https://i.imgur.com/uYdKmZC.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201473,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "a79d0528-d084-4830-84d2-14105501b34a",
                    "productName": "Organic Pepper Cheddar",
                    "productUnitPrice": 1410.0,
                    "productImage": "https://i.imgur.com/vCjHnFS.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Pepper Cheddar",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201476,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "f5211b01-8658-43d2-b597-c8fe73dcb940",
                    "productName": "Organic Chilli Cheddar",
                    "productUnitPrice": 1375.0,
                    "productImage": "https://i.imgur.com/OhPA91j.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201474,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "201549f5-14c2-473f-91ee-658dc0e6b885",
                    "productName": "Organic Pepper Cheddar",
                    "productUnitPrice": 282.0,
                    "productImage": "https://i.imgur.com/vCjHnFS.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201471,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "877792ab-f266-48f6-bd1c-b19e36432043",
                    "productName": "Organic Chilli Cheddar",
                    "productUnitPrice": 275.0,
                    "productImage": "https://i.imgur.com/OhPA91j.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201469,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1999,
                    "trackInventory": true
                },
                {
                    "id": "cd281e25-e59a-4337-bb85-de3e96490b45",
                    "productName": "Organic Pizza Cheese",
                    "productUnitPrice": 263.0,
                    "productImage": "https://i.imgur.com/fJhXg9p.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201472,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1999,
                    "trackInventory": true
                },
                {
                    "id": "f15bd401-6edc-4e7f-842d-a228186aabd4",
                    "productName": "Organic Greek yogurt",
                    "productUnitPrice": 40.0,
                    "productImage": "https://i.imgur.com/dtsHT6J.png",
                    "productSubType": 1,
                    "productUnitSize": "100 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Curd",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201443,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1999,
                    "trackInventory": true
                },
                {
                    "id": "361d36ed-66ed-4498-951b-a1973c6eb820",
                    "productName": "Organic smoked cheddar",
                    "productUnitPrice": 1400.0,
                    "productImage": "https://i.imgur.com/I3T6uY2.png",
                    "productSubType": 2,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheedar Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201442,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "b1208694-015b-431d-b662-d441616dbb93",
                    "productName": "Desi Cow Ghee",
                    "productUnitPrice": 600.0,
                    "productImage": "https://i.imgur.com/DRGvOfc.png",
                    "productSubType": 2,
                    "productUnitSize": "300 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Cow Ghee",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 313,
                    "productSubCategory": 739,
                    "productParent": 10201463,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "57a4eacf-d681-4a24-bdaa-ed1e4f01f6d2",
                    "productName": "Organic Table Butter",
                    "productUnitPrice": 560.0,
                    "productImage": "https://i.imgur.com/ubS7tax.png",
                    "productSubType": 2,
                    "productUnitSize": "500 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Table butter",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201459,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "2985d52f-eb50-468f-9018-2bd4fe61eb85",
                    "productName": "Organic Cooking Butter",
                    "productUnitPrice": 550.0,
                    "productImage": "https://i.imgur.com/2n1XEFh.png",
                    "productSubType": 2,
                    "productUnitSize": "500 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cooking Butter",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201461,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "6ce87f48-c0d0-4062-8a11-7eb0feb20ca6",
                    "productName": "Organic Table Butter",
                    "productUnitPrice": 225.0,
                    "productImage": "https://i.imgur.com/ubS7tax.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Table butter",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201458,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1997,
                    "trackInventory": true
                },
                {
                    "id": "c58b1708-d3c0-492e-8d7c-a50713c30f91",
                    "productName": "Akshayaklapa Organic set curd",
                    "productUnitPrice": 40.0,
                    "productImage": "https://i.imgur.com/FaDndaq.png",
                    "productSubType": 1,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayaklapa Set Curd",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201454,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1993,
                    "trackInventory": true
                },
                {
                    "id": "2a9e8e88-42ea-4cee-a0c3-31167755515c",
                    "productName": "A2 Probiotic Butter Milk Spiced",
                    "productUnitPrice": 15.0,
                    "productImage": "https://i.imgur.com/dVqWOxG.png",
                    "productSubType": 2,
                    "productUnitSize": "200 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Butter Milk Spiced",
                    "status": 1,
                    "flashStatus": 3,
                    "strikePrice": 20.0,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201456,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 102,
                    "isDetailsAvailable": true,
                    "productQuantity": 1992,
                    "maxQuantityForOffer": 1111,
                    "trackInventory": true
                },
                {
                    "id": "aee0511b-4267-4a85-b85e-f82bcc002351",
                    "productName": "A2 Butter Milk Spiced",
                    "productUnitPrice": 20.0,
                    "productImage": "https://i.imgur.com/dVqWOxG.png",
                    "productSubType": 1,
                    "productUnitSize": "200 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Butter Milk Spiced",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201457,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1997,
                    "trackInventory": true
                },
                {
                    "id": "8454337e-9c34-4f0a-9544-afeadd86fd2b",
                    "productName": "Organic Greek yogurt",
                    "productUnitPrice": 160.0,
                    "productImage": "https://i.imgur.com/dtsHT6J.png",
                    "productSubType": 1,
                    "productUnitSize": "400 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Curd",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201444,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "07813dc1-88d4-4041-aab0-8bd4a6f9d1b3",
                    "productName": "Akshyakalpa Organic curd",
                    "productUnitPrice": 150.0,
                    "productImage": "https://i.imgur.com/WKPrAGS.png",
                    "productSubType": 1,
                    "productUnitSize": "1 kg",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa Curd",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201453,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1996,
                    "trackInventory": true
                },
                {
                    "id": "b35a7eaf-43ba-42ed-85be-eeb24b44db8b",
                    "productName": "Lactose free milk",
                    "productUnitPrice": 160.0,
                    "productImage": "https://i.imgur.com/hk2dAjg.png",
                    "productSubType": 2,
                    "productUnitSize": "1000 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Lactose free milk",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201446,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "2832c630-eb76-4433-9af7-0184ac5bc369",
                    "productName": "Cow Milk pasteurized",
                    "productUnitPrice": 120.0,
                    "productImage": "https://i.imgur.com/2hm71ct.png",
                    "productSubType": 2,
                    "productUnitSize": "1000 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Cow milk",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201449,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "679a9eb5-048f-486c-875a-8f4186fb1eab",
                    "productName": "Cow Milk pasteurized",
                    "productUnitPrice": 40.0,
                    "productImage": "https://i.imgur.com/jWYjGMn.png",
                    "productSubType": 2,
                    "productUnitSize": "500 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "pasteurized",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201448,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "8f25bf04-0875-44d6-85f3-4624f2cb5854",
                    "productName": "Akshayakalpa  Organic curd",
                    "productUnitPrice": 20.0,
                    "productImage": "https://i.imgur.com/TQDoN7Y.png",
                    "productSubType": 1,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa-Curd",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201452,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1997,
                    "trackInventory": true
                },
                {
                    "id": "04ea928a-3ebc-4309-83ae-896665920b34",
                    "productName": "A2  pasteurized milk",
                    "productUnitPrice": 140.0,
                    "productImage": "https://i.imgur.com/Ag2uu2j.png",
                    "productSubType": 2,
                    "productUnitSize": "1000 ml",
                    "fulfilledByVendor": true,
                    "productAlias": " pasteurized milk",
                    "status": 2,
                    "flashStatus": 3,
                    "productCategory": 310,
                    "productSubCategory": 739,
                    "productParent": 10201450,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "abe54004-29c6-4cca-a011-1935ba55c22c",
                    "productName": "Akshayakalpa Organic curd",
                    "productUnitPrice": 60.0,
                    "productImage": "https://i.imgur.com/WjFq4Vp.png",
                    "productSubType": 1,
                    "productUnitSize": "500 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayakalpa Curd",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201451,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "081bc53c-92ab-4b60-8a5e-b36dac60b8cc",
                    "productName": "Organic Cooking Butter",
                    "productUnitPrice": 250.0,
                    "productImage": "https://i.imgur.com/2n1XEFh.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cooking Butter",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201460,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "9685c3c5-ec00-4fe7-a714-cbdec102aa8b",
                    "productName": "Organic  Cooking Butter",
                    "productUnitPrice": 230.0,
                    "productImage": "https://i.imgur.com/8DeUsN3.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cooking Butter",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 314,
                    "productSubCategory": 739,
                    "productParent": 10201462,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "8d848942-7cfa-4aa9-bcf6-9e9369fb3950",
                    "productName": "Akshayakalapa Organic set curd",
                    "productUnitPrice": 80.0,
                    "productImage": "https://i.imgur.com/omavj6O.png",
                    "productSubType": 1,
                    "productUnitSize": "400 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Akshayaklapa Set Curd",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 312,
                    "productSubCategory": 739,
                    "productParent": 10201455,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1997,
                    "trackInventory": true
                },
                {
                    "id": "3a9cf806-d951-4ba3-9513-2d2b528b7af0",
                    "productName": "Organic Ghee",
                    "productUnitPrice": 685.0,
                    "productImage": "https://i.imgur.com/TOEbrAz.png",
                    "productSubType": 2,
                    "productUnitSize": "490 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Organic Ghee",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 313,
                    "productSubCategory": 739,
                    "productParent": 10201465,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1993,
                    "trackInventory": true
                },
                {
                    "id": "77d9561b-bf1f-481e-9658-946ecd17524a",
                    "productName": "Organic Aged Cheddar",
                    "productUnitPrice": 285.0,
                    "productImage": "https://i.imgur.com/cgrGvMf.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201468,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "98fc5068-834c-40ca-84d9-7434cce79f55",
                    "productName": "Organic Ghee",
                    "productUnitPrice": 280.0,
                    "productImage": "https://i.imgur.com/TOEbrAz.png",
                    "productSubType": 2,
                    "productUnitSize": "200 ml",
                    "fulfilledByVendor": true,
                    "productAlias": "Ghee",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 313,
                    "productSubCategory": 739,
                    "productParent": 10201464,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1998,
                    "trackInventory": true
                },
                {
                    "id": "e933b0c1-90f8-4d74-add8-6fbee2ccd6fb",
                    "productName": "Organic Mild Cheddar",
                    "productUnitPrice": 260.0,
                    "productImage": "https://i.imgur.com/7YgyJ9l.png",
                    "productSubType": 2,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Cheese",
                    "status": 1,
                    "flashStatus": 3,
                    "productCategory": 315,
                    "productSubCategory": 739,
                    "productParent": 10201470,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 2000,
                    "trackInventory": true
                },
                {
                    "id": "0f48452f-7ba5-4cfe-96c9-94c21d1e125b",
                    "productName": "Organic Malai Paneer",
                    "productUnitPrice": 105.0,
                    "productImage": "https://i.imgur.com/cgrGvMf.png",
                    "productSubType": 1,
                    "productUnitSize": "200 gm",
                    "fulfilledByVendor": true,
                    "productAlias": "Paneer ",
                    "status": 1,
                    "flashStatus": 3,
                    "strikePrice": 140.0,
                    "productCategory": 317,
                    "productSubCategory": 739,
                    "productParent": 10201466,
                    "buildingId": "da4a0aa3-0336-403b-b3b0-02353945fb0a",
                    "productTypeNo": 106,
                    "isDetailsAvailable": true,
                    "productQuantity": 1976,
                    "maxQuantityForOffer": 199,
                    "trackInventory": true
                }
            ],
            "productParentId": 10201467,
            "productParent": 10201467,
            "status": 1
        }
    }
]